source 'http://rubygems.org'

gem 'rails', '3.0.5'
gem 'rake', '~> 0.8.7'
gem 'pg'
gem 'devise'
gem 'cancan'
gem 'nifty-generators'
gem 'aws-s3'
gem 'paperclip'
gem 'acts-as-taggable-on', '~>2.1.0'
gem 'ancestry'