source 'http://rubygems.org'
ruby '2.1.2'

gem 'rails', '3.0.5'
gem 'rake', '~> 0.8.7'
gem 'pg'
gem 'devise'
gem 'cancan'
gem 'nifty-generators'
gem 'aws-sdk'
gem 'paperclip'
gem 'acts-as-taggable-on', '~>2.1.0'
gem 'ancestry'
gem 'feedjira'
gem 'kaminari'
