development:
  adapter: postgresql
  encoding: unicode
  database: lab_dev
  pool: 5
  username: sharpei
  password:

test:
    adapter: postgresql
    encoding: unicode
    database: lab_test
    pool: 5
    username: sharpei
    password:

production:
    adapter: postgresql
    encoding: unicode
    database: lab_prod
    pool: 5
    username: ryan
    password: postgres
